riscv64: Fix missing Zicsr Zifencei in GCC >= 11
In GCC version >= 11, since the the version of RISC-V ISA used is 20191213,
csrr*/csrw* are not in I extension anymore. This lead to failed
compilation when using csrr*/csrw* instructions, for example:
> Error: unrecognized opcode `csrw stvec,t0'

This enable Zicsr and Zifencei extension when GCC version is >= 11.